function [output, act_h, act_a] = Forward(W, b, X)
% [OUT, act_h, act_a] = Forward(W, b, X) performs forward propogation on the
% input data 'X' uisng the network defined by weights and biases 'W' and 'b'
% (as generated by InitializeNetwork(..)).
% This function should return the final softmax output layer activations in OUT,
% as well as the hidden layer pre activations in 'act_h', and the hidden layer post
% activations in 'act_a'.

act_h = X * W{1} + b{1}';
act_a = 1./(1+exp(-act_h));
out_all = act_a * W{2} + b{2}';
A = exp(out_all);
out = bsxfun(@rdivide,A,sum(A')');
end
